config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :replies, only: [:create, :edit, :update, :destroy]
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  resources :categories, only: [:show]
  resources :users, only: [:show, :edit, :update] do
    member do
      get :post
      get :reply
      get :draft
      get :collect
      get :friend
      post :friend_request
      post :friend_accept
      post :friend_ignore   
    end
  end

  namespace :admin do
    root "categories#index"
    resources :users, only:[:index, :update]
    resources :categories
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_create :generate_authentication_token
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, ImageUploader

  has_many :posts, dependent: :destroy 

  has_many :replies, dependent: :restrict_with_error
  has_many :replied_posts, through: :replies, source: :post

  has_many :collects, dependent: :destroy
  has_many :collected_posts, through: :collects, source: :post

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, source: :user

  has_many :vieweds, dependent: :restrict_with_error
  has_many :viewed_posts, through: :vieweds, source: :post
  
  def admin?
    self.role == "Admin"
  end

  def friend?(user)
    friendship_record = Friendship.where(user_id: user.id, friend_id: self.id).or(Friendship.where(user_id: self.id, friend_id: user.id))
    if friendship_record.any?
      # 有好友記錄
      if friendship_record.first.status == "accept"
        return "friend"
      else
        return "exist"
      end
    else
      # 沒有好友記錄
      return "none"
    end
  end

  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all
    
  end

  def update
    @user = User.find(params[:id])
    @user.update(role: params[:role])
    if @user.save
      redirect_to admin_users_path
      flash[:notice] = "Authorization update succeeded"
    else
      flash[:alert] = "Not allow"
      render :index
    end
  end

  private
  def user_params
    params.require(:user).permint(:name, :eamil, :role)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:accept, :ignore]

  def show
    
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    
    if @user.save
      flash[:notice] = "Profile was successfully updated"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "Profile was failed to update!"
      render :edit
    end
  end

  def post
    @published = @user.posts.published
  end

  def draft
    @drafts = @user.posts.drafts
    unless @user == current_user
      redirect_to user_path(@user)
    end 
  end

  def reply
    @replies = @user.replies.order(id: :desc)
  end

  def collect
    @collects = @user.collects
  end

  def friend
    @waiting_for_responses = Friendship.where(user_id: @user.id, status: "pending")
    @requests = Friendship.where(friend_id: @user.id, status: "pending")
    @friendships = Friendship.where(user_id: @user.id, status: "accept").or(Friendship.where(friend_id: @user.id, status: "accept"))
  end

  def friend_request
    if current_user != @user 
      @friend_request = Friendship.new(user_id: current_user.id, friend_id: @user.id)
      @friend_request.save
    end
  end

  def friend_accept
    @friend_request = Friendship.find(params[:id])
    @friend_request.status = "accept"
    @friend_request.save
  end

  def friend_ignore
    @friend_request = Friendship.find(params[:id])
    @friend_request.status = "ignore"
    @friend_request.save
  end

  private

  def set_user
    @user = User.find(params[:id])
    return @user
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :avatar )
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/collect.html.erb
<%= render partial: 'shared/profile' %>
<table class="table table-hover text-center">
  <tbody>
    <% @collects.each do |collect| %>
      <tr data-link="<%= post_path(collect.post) %>" class="text-center" >
        <td width="211px"><h5 class="text-info"><%= collect.post.title %></h5></td>
        <td width="251px"></td>
        <td width="231px"></td>
        <td width="216px">
          <div id="collect-<%= collect.post.id %>">
            <%= render partial: "shared/collect", locals: { post: collect.post } %>
          </div>
        </td>
        <td width="222px"></td>
      </tr>
    <% end %>
  </tbody>
</table>
<script>
  $("tr[data-link]").click(function(event) {
    if (!$(event.target).is('a')){
      window.location = $(this).data("link")
    };
  });
</script>

app/views/users/draft.html.erb
<%= render partial: 'shared/profile' %>
<table class="table table-hover">
  <tbody>
    <% @drafts.each do |draft| %>
      <tr  class="text-center" >
        <td><h5><%= link_to draft.title, post_path(draft), class:"text-info" %></h5></td>
        <td class="text-capitalize"><h5><%= draft.status %></h5></td>
        <td><h5><%= draft.created_at.to_date %></h5></td>
        <td>
        <% if draft.user == current_user %>
          <%= link_to edit_post_path(draft) do %>
          <h4 class="text-danger"><%= fas_icon 'fas fa-edit' %></h4> 
        <% end %>
        </td>
        <td>
          <%= link_to post_path(draft), method: :delete, data: { confirm: "Are you sure?" } do %>
            <h4 class="text-danger"><%= fas_icon 'fas fa-trash-alt' %></h4>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container"><br><br>
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.text_area :introduction,size: "30x10", class: "form-control" %>
    </div>
    <div class="form-group">  
      <%= image_tag @user.avatar, width: "200px" if @user.avatar? %>
      <%= f.file_field :avatar %>
    </div>
      <%= f.submit "Submit", class: "btn btn-outline-success" %>
  <% end %>
</div>

app/views/users/friend.html.erb
<%= render partial: 'shared/profile' %>
  <div class="card">
    <h5 class="card-header text-center">Waiting for response</h5>
    <div class="card-body row">
      <% @waiting_for_responses.each do |response| %>
        <% if response.friend.id %>
        <span class="card-text text-center p-1">
          <%= link_to user_path(response.friend.id) do %>
            <%= image_tag response.friend.avatar, width: '100px' %>
            <h5 class="text-info"><%= response.friend.name %></h5>
          <% end %>
        </span>
        <% end %>
      <% end %>
    </div>
    <h5 class="card-header text-center">Friend Request</h5>
    <div class="card-body row">
      <% @requests.each do |request| %>
      <span class="card-text text-center p-1" id="request-<%= request.id %>">
        <%= link_to user_path(request.user) do %>
          <%= image_tag request.user.avatar, width: '100px' %>
          <h5 class="text-info"><%= request.user.name %></h5>
        <% end %>
        <% if current_user == @user %>
          <%= link_to friend_accept_user_path(request.id), method: :post, class: "btn btn-sm", remote: true do %>
          <h4><%= fa_icon "check-circle 2x" %></h4>
          <% end %>
          <%= link_to friend_ignore_user_path(request.id), method: :post, class: "btn btn-sm text-danger", remote: true do %>
          <h4><%= fa_icon "times-circle 2x" %></h4>  
          <% end %>
        <% end %>
      </span>
      <% end %>
    </div>

    <h5 class="card-header text-center">Friend List</h5>
    <div class="card-body row" id="friend-list">
      <% @friendships.each do |friendship| %>
        <% if @user != friendship.user %>
          <% friend = friendship.user %>
        <% else %>
          <% friend = friendship.friend %>
        <% end %>
        <span class="card-text text-center p-1">
          <%= link_to user_path(friend) do %>
            <%= image_tag friend.avatar, width: '100px' %>
            <h5 class="text-info"><%= friend.name %></h5>
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/users/friend_accept.js.erb
$("#request-<%= @friend_request.id %>").children(".btn").remove();
var friend_user = $("#request-<%= @friend_request.id %>");
$("#friend-list").append(friend_user);

app/views/users/friend_ignore.js.erb
$("#request-<%= @friend_request.id %>").remove();

app/views/users/friend_request.js.erb
var unable_button = '<%= j render partial: "shared/add_friend"%>';
$("#friend-btn-<%= @user.id %>").children().remove();
$("#friend-btn-<%= @user.id %>").html(unable_button);

app/views/users/post.html.erb
<%= render partial: 'shared/profile' %>
<table class="table table-hover">
  <tbody>
    <% @published.each do |publish| %>
      <tr class="text-center" >
        <td><h5><%= link_to publish.title, post_path(publish), class:"text-info" %></h5></td>
        <td class="text-capitalize"><h5><%= publish.status %></h5></td>
        <td><h5><%= publish.created_at.to_date %></h5></td>
        <td>
        <% if publish.user == current_user %>
          <%= link_to edit_post_path(publish) do %>
            <h4 class="text-danger"><%= fas_icon 'fas fa-edit' %></h4> 
          <% end %>
        </td>
        <td>
          <%= link_to post_path(publish), method: :delete, data: { confirm: "Are you sure?" } do %>
            <h4 class="text-danger"><%= fas_icon 'fas fa-trash-alt' %></h4>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/reply.html.erb
<%= render partial: 'shared/profile' %>
<div class="container">
  <div class="row">
    <% @replies.each do |reply| %>
      <div class="col-12 col-md-7 offset-md-2">
        <h5 class="font-weight-bold p-1">
          <%= link_to reply.post.title, post_path(reply.post), class:"text-info" %>
        </h5>
        <div id="<%= reply.id %>">
          <div class="card">
            <div class="card-body p-5">
              <p><%= reply.comment%></p>
            </div>
          </div>
          <% if reply.user == current_user %>
            <%= link_to post_reply_path(reply.post, reply), method: :delete, data: { confirm: "Are you sure?" } do %>
              <h3 class="text-danger float-right p-1"><%= fas_icon 'fas fa-trash-alt' %></h3>
            <% end %>
            <%= link_to edit_post_reply_path(reply.post, reply), remote: true do %>
              <h3 class="text-dark float-right  p-1"><%= fas_icon 'fas fa-edit' %></h3>
            <% end %>
          <% end %>
        </div>
      </div>   
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: 'shared/profile' %>