config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :replies, only: [:create, :edit, :update, :destroy]
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  resources :categories, only: [:show]
  resources :users, only: [:show, :edit, :update] do
    member do
      get :post
      get :reply
      get :draft
      get :collect
      get :friend
      post :friend_request
      post :friend_accept
      post :friend_ignore   
    end
  end

  namespace :admin do
    root "categories#index"
    resources :users, only:[:index, :update]
    resources :categories
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader

  belongs_to :user, optional: true

  has_many :replies, dependent: :destroy
  has_many :replied_users, through: :replies, source: :user

  has_many :collects, dependent: :destroy
  has_many :collected_users, through: :collects, source: :user
  
  has_many :vieweds, dependent: :destroy
  has_many :veiwed_users, through: :vieweds, source: :user

  has_many :post_categories ,dependent: :destroy
  has_many :categories, through: :post_categories
  

  def self.published
    where(status: "published").all
  end
 
  
  def self.drafts
    where(:status => "draft").all
  end

  def is_collected?(user)
    self.collected_users.include?(user)
  end

  def pageviews
    self.viewed_count += 1
    save!
  end

end

app/views/shared/_add_friend.html.erb
<% if @user != current_user && @user.friend?(current_user) == "none" %>
  <span id="friend-btn-<%= @user.id %>">
    <%= link_to "Add Friend", friend_request_user_path(@user), method: :post, class: "btn btn-dark btn-sm mb-1", remote: true %>
  </span>
<% elsif @user.friend?(current_user) == "friend" %>
  <span class="badge badge-pill badge-success md-1">Friend</span>
<% elsif @user.friend?(current_user) == "exist" %>
  <button type="button" class="btn btn-secondary btn-sm mb-1" disabled>Add Friend</button>
<% end %>

app/views/shared/_collect.html.erb
<% if post.is_collected?(current_user) %>
  <li class="nav-link"><%= link_to 'Uncollect', uncollect_post_path(post), method: :post, remote: true, class:"btn btn-outline-success"  %></li>
<% else %>
  <li class="nav-link"><%= link_to 'Collect', collect_post_path(post), method: :post, remote: true, class:"btn btn-outline-success" %></li>
<% end %>

app/views/shared/_form.html.erb
<div class="container"><br><br>
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.text_field :title, placeholder: "title", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.text_area :content, class: "form-control", size: "30x10" %>
    </div>
    <div class="form-group">
      <%#= image_tag @post.image, width: "200px", if @post.image? %>
      <%= f.file_field :image %>
    </div>
    <div class="form-group">
      Who Can See : 
      <div class="form-check form-check-inline">
        <%= f.radio_button :purview, "All", :checked => true, class: "form-check-input" %>
        <label class="form-check-label">All</label>
      </div>
      <div class="form-check form-check-inline">
        <%= f.radio_button :purview, "Friend", class: "form-check-input" %>
        <label class="form-check-label">Friend</label>
      </div>
      <div class="form-check form-check-inline">
        <%= f.radio_button :purview, "Myself", class: "form-check-input"  %>
        <label class="form-check-label">Myself</label>
      </div> 
      <br/>
    </div>
    <div class="form-group">
      Category:
      <div class="form-check form-check-inline">   
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, {}, { multiple: true,class: "form-check-input "}  do |c| %>
          <%= c.check_box(class: "form-check-input") %> 
          <div class="p-1"><%= c.object.name%></div>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      Status:    
    </div>
    <div class="form-group">
      <%= f.submit "Save Draft", class: "btn btn"%>
      <%= f.submit "Submit", class: "btn btn" %>
    </div>
  <% end %>
</div>











        

app/views/shared/_post_list.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr class="text-center text-black-50">
        <th scope="col"><%= sort_link(@ransack, :replies_count, "Replies count", default_order: :desc) %></th>
        <th scope="col">Title</th>
        <th scope="col"><%= sort_link(@ransack, :replies_created_at, "Last replied at", default_order: :desc) %></th>
        <th scope="col"><%= sort_link(@ransack, :viewed_count, "Viewed count", default_order: :desc) %></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %> 
        <% if post.purview == "All" || current_user != nil &&
        post.purview == "Friend" && current_user.friend?(post.user) == "friend" ||
         post.user == current_user %> 
          <tr data-link="<%=post_path(post)%>" class="text-center" >
            <td><%= post.replies_count %></td>
            <td><%= post.title %></td>
            <td>
            <% if post.replies_count != 0 %>
              <%= post.replies.last.created_at.strftime("%Y-%m-%d") %>
            <% end %>
            </td>       
            <td><span class="mr-3 text-right"><%= fas_icon('fas fa-eye') %></span><%= post.viewed_count %></td>
          </tr>
        <% end %>
      <% end %>  
    </tbody>
  </table>
</div>
<script>$("tr[data-link]").click(function() {
  window.location = $(this).data("link")
})</script>

<div class="pagination justify-content-center">
  <p class="text-info"><%= paginate @posts %></p>
</div>
      
 

app/views/shared/_profile.html.erb
<div class="jumbotron jumbotron-fluid p-3 mb-0">
  <div class="container">
    <div class="row">
      <div class="col-6 col-md-4 text-center">
        <%= image_tag @user.avatar, size: "240x200" if @user.avatar? %>
        <h5 class="w-100 ">
          <%= link_to @user.name, user_path(@user), class: "text-info" %>
        </h5>
      </div>
      <div class="col-12 col-md-6">
        <%= @user.introduction %>
        <div class="col-12 col-md-12">
          <% if @user.email = current_user.email %>
            <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-outline-success float-right" %>
          <% end %>
        </div>
      </div>  
    </div>
  </div> 
</div>
<br>
<ul class="nav nav-tabs nav-fill">
  <li class="nav-item">
    <%= link_to 'My Post', post_user_path(@user), class: "nav-link text-success font-weight-bold #{'active' if @published.present?}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'My Comment', reply_user_path(@user), class: "nav-link text-success font-weight-bold #{'active' if @replies.present?}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'My Collect', collect_user_path(@user), class: "nav-link text-success font-weight-bold #{'active' if @collects.present?}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'My Draft', draft_user_path(@user), class: "nav-link text-success font-weight-bold #{'active' if @drafts.present?}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'My friend', friend_user_path(@user), class: "nav-link text-success font-weight-bold #{'active' if @friendships.present?}" %>  
  </li>
</ul>