config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :replies, only: [:create, :edit, :update, :destroy]
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  resources :categories, only: [:show]
  resources :users, only: [:show, :edit, :update] do
    member do
      get :post
      get :reply
      get :draft
      get :collect
      get :friend
      post :friend_request
      post :friend_accept
      post :friend_ignore   
    end
  end

  namespace :admin do
    root "categories#index"
    resources :users, only:[:index, :update]
    resources :categories
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :post_categories, dependent: :restrict_with_error
  has_many :posts, through: :post_categories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  
  before_action :set_category, only: [:update, :destroy]

  def index
    @categories = Category.all
    if params[:id]
      set_category
    else
      @category = Category.new
    end 
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "New category was successfully created"
      redirect_to admin_root_path
    else
      @categories = Category.all
      render :index
    end
  end

  

  def update
    @category.update(category_params)
    if @category.save
      redirect_to admin_root_path
      flash[:notice] = "Category was successfully update"
    else
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_root_path
  end

  private

  def set_category
   @category = Category.find(params[:id]) 
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @ransack = @category.posts.where(status: "published").ransack(params[:q])
    @posts = @ransack.result(distinct: true).page(params[:page]).per(20)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">

    <div class="container-fluid">
        <%= link_to 'Category List', admin_categories_path, class: "btn btn-default" %>|
        <%= link_to 'User List', admin_users_path, class: "btn btn-default" %>
    </div>
    <br><br>    
    <div class="form-inline">
      <%= form_for [:admin, @category] do |f| %>     
          <%= f.text_field :name, class: "form-control" %>
        <%= f.submit class: "btn btn-info" %>
        <% if @category.errors.any? %>
          <%= @category.errors.full_messages.to_sentence %>
        <% end %>
      <% end %>
    </div> 
    <br><br><br>
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th scope="col">name</th>
          <th colspan="col" >option</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to 'Edit', admin_categories_path(id: category.id)  %>
            <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?" }  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>