config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :replies, only: [:create, :edit, :update, :destroy]
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  resources :categories, only: [:show]
  resources :users, only: [:show, :edit, :update] do
    member do
      get :post
      get :reply
      get :draft
      get :collect
      get :friend
      post :friend_request
      post :friend_accept
      post :friend_ignore   
    end
  end

  namespace :admin do
    root "categories#index"
    resources :users, only:[:index, :update]
    resources :categories
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #003377;">
      <%= link_to 'Story', posts_path, class: "navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Feeds", feeds_posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Post", new_post_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
            <li class="nav-item">
               <span class="nav-link"><%= current_user.email %></span>
            </li>
              <% if current_user.admin? %>
                <li class="nav-item">
                  <%= link_to "(Admin)", admin_root_path, class: "nav-link" %>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to "Profile", post_user_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">  
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }, class: "nav-link" %>
              </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>    
        </ul>
      </div>
    </nav>
    <% if flash[:notice] %> 
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if flash[:alert] %> 
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>
<script type="text/javascript">
  $( document ).ready(function() {
    setTimeout(function(){ $(".alert").hide() },5000)
  });
</script>